export const ListData = [
  {
    "id": "1",
    "title": "Initialize React project with Vite",
    "status": "DONE",
    "comments": 2,
    "assignee": { "name": "Ritesh Kumar", "avatar": "RK" },
    "dueDate": "Dec 1, 2025",
    "dueDateWarning": false,
    "priority": "highest",
    "labels": ["setup", "config"],
    "created": "Dec 1, 2025",
    "updated": "Dec 2, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "2",
    "title": "Configure ESLint and Prettier",
    "status": "DONE",
    "comments": 0,
    "assignee": { "name": "Ritesh Kumar", "avatar": "RK" },
    "dueDate": "Dec 2, 2025",
    "dueDateWarning": false,
    "priority": "medium",
    "labels": ["dx"],
    "created": "Dec 1, 2025",
    "updated": "Dec 2, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "3",
    "title": "Setup React Router DOM",
    "status": "DONE",
    "comments": 1,
    "assignee": null,
    "dueDate": "Dec 5, 2025",
    "dueDateWarning": false,
    "priority": "high",
    "labels": ["routing"],
    "created": "Dec 3, 2025",
    "updated": "Dec 5, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "4",
    "title": "Create Application Layout (Sidebar + Navbar)",
    "status": "IN PROGRESS",
    "comments": 5,
    "assignee": { "name": "Ritesh Kumar", "avatar": "RK" },
    "dueDate": "Dec 20, 2025",
    "dueDateWarning": true,
    "priority": "highest",
    "labels": ["ui", "layout"],
    "created": "Dec 10, 2025",
    "updated": "Dec 18, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "5",
    "title": "Implement Dark Mode Theme Context",
    "status": "IN PROGRESS",
    "comments": 3,
    "assignee": { "name": "Ritesh Kumar", "avatar": "RK" },
    "dueDate": "Dec 22, 2025",
    "dueDateWarning": true,
    "priority": "medium",
    "labels": ["theme", "ui"],
    "created": "Dec 12, 2025",
    "updated": "Dec 20, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "6",
    "title": "Build 'Create Task' Modal Form",
    "status": "TODO",
    "comments": 0,
    "assignee": null,
    "dueDate": null,
    "dueDateWarning": false,
    "priority": "high",
    "labels": ["feature", "forms"],
    "created": "Dec 15, 2025",
    "updated": "Dec 15, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "7",
    "title": "Design Drag and Drop Board logic",
    "status": "TODO",
    "comments": 8,
    "assignee": null,
    "dueDate": "Jan 10, 2026",
    "dueDateWarning": false,
    "priority": "highest",
    "labels": ["complex", "feature"],
    "created": "Dec 15, 2025",
    "updated": "Dec 15, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "8",
    "title": "Integrate Firebase Authentication",
    "status": "TODO",
    "comments": 0,
    "assignee": null,
    "dueDate": null,
    "dueDateWarning": false,
    "priority": "high",
    "labels": ["backend", "auth"],
    "created": "Dec 16, 2025",
    "updated": "Dec 16, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "9",
    "title": "Create reusable Button and Input components",
    "status": "DONE",
    "comments": 0,
    "assignee": { "name": "Ritesh Kumar", "avatar": "RK" },
    "dueDate": "Dec 8, 2025",
    "dueDateWarning": false,
    "priority": "low",
    "labels": ["ui-kit"],
    "created": "Dec 5, 2025",
    "updated": "Dec 8, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "10",
    "title": "Fix overflow issue in Sidebar",
    "status": "IN PROGRESS",
    "comments": 1,
    "assignee": { "name": "Ritesh Kumar", "avatar": "RK" },
    "dueDate": "Dec 21, 2025",
    "dueDateWarning": true,
    "priority": "medium",
    "labels": ["bug", "css"],
    "created": "Dec 19, 2025",
    "updated": "Dec 20, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "11",
    "title": "Set up Redux Toolkit for state management",
    "status": "DONE",
    "comments": 2,
    "assignee": { "name": "Ritesh Kumar", "avatar": "RK" },
    "dueDate": "Dec 10, 2025",
    "dueDateWarning": false,
    "priority": "highest",
    "labels": ["state", "setup"],
    "created": "Dec 6, 2025",
    "updated": "Dec 10, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "12",
    "title": "Create 404 Not Found Page",
    "status": "TODO",
    "comments": 0,
    "assignee": null,
    "dueDate": null,
    "dueDateWarning": false,
    "priority": "lowest",
    "labels": ["ui"],
    "created": "Dec 18, 2025",
    "updated": "Dec 18, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "13",
    "title": "Refactor Project Card Component",
    "status": "TODO",
    "comments": 0,
    "assignee": null,
    "dueDate": null,
    "dueDateWarning": false,
    "priority": "low",
    "labels": ["refactor"],
    "created": "Dec 18, 2025",
    "updated": "Dec 18, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "14",
    "title": "Implement Task Filtering by Assignee",
    "status": "TODO",
    "comments": 4,
    "assignee": null,
    "dueDate": "Jan 5, 2026",
    "dueDateWarning": false,
    "priority": "medium",
    "labels": ["feature"],
    "created": "Dec 20, 2025",
    "updated": "Dec 20, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "15",
    "title": "Add loading skeletons for dashboard",
    "status": "IN PROGRESS",
    "comments": 0,
    "assignee": { "name": "Ritesh Kumar", "avatar": "RK" },
    "dueDate": "Dec 25, 2025",
    "dueDateWarning": false,
    "priority": "medium",
    "labels": ["ux"],
    "created": "Dec 21, 2025",
    "updated": "Dec 21, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "16",
    "title": "Research chart libraries for Analytics",
    "status": "DONE",
    "comments": 1,
    "assignee": { "name": "Ritesh Kumar", "avatar": "RK" },
    "dueDate": "Dec 14, 2025",
    "dueDateWarning": false,
    "priority": "low",
    "labels": ["research"],
    "created": "Dec 12, 2025",
    "updated": "Dec 14, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "17",
    "title": "Implement search functionality in header",
    "status": "TODO",
    "comments": 0,
    "assignee": null,
    "dueDate": null,
    "dueDateWarning": false,
    "priority": "medium",
    "labels": ["feature"],
    "created": "Dec 20, 2025",
    "updated": "Dec 20, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "18",
    "title": "Write unit tests for utility functions",
    "status": "TODO",
    "comments": 0,
    "assignee": null,
    "dueDate": "Jan 15, 2026",
    "dueDateWarning": false,
    "priority": "high",
    "labels": ["testing"],
    "created": "Dec 21, 2025",
    "updated": "Dec 21, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "19",
    "title": "Optimize bundle size",
    "status": "TODO",
    "comments": 1,
    "assignee": null,
    "dueDate": null,
    "dueDateWarning": false,
    "priority": "low",
    "labels": ["performance"],
    "created": "Dec 21, 2025",
    "updated": "Dec 21, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  },
  {
    "id": "20",
    "title": "Deploy initial version to Vercel",
    "status": "TODO",
    "comments": 0,
    "assignee": null,
    "dueDate": "Jan 1, 2026",
    "dueDateWarning": false,
    "priority": "highest",
    "labels": ["deployment"],
    "created": "Dec 22, 2025",
    "updated": "Dec 22, 2025",
    "reporter": { "name": "Ritesh Kumar", "avatar": "RK" }
  }
]